# Generated by Django 4.1.4 on 2022-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.IntegerField(null=True, verbose_name='Ürün Stok Sayısı'),
        ),
    ]
