# Generated by Django 4.1.4 on 2023-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_product_stok_shopbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbuy',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='Beden'),
        ),
    ]
